#!/usr/bin/env bash

cd $(dirname $0)

(
if [ $# -eq 0 ]; then
  echo "--help"
else
  for i;
  do
    echo "'$i'"
  done
fi
#) | xargs docker run --shm-size=1gb -v `pwd`:/tmp/screenshot docker_capture_web  ## working
#) | xargs docker run -v `pwd`:/tmp/screenshot mokemokechicken/capture_web
#) | xargs docker run -v `pwd`:/tmp/screenshot docker_capture_web_otorio
) | xargs docker run --shm-size=1gb -v `pwd`:/tmp/screenshot docker_capture_web_otorio
