#!/usr/bin/env bash

cd $(dirname $0)

#(
if [ $# -eq 0 ]; then
  echo "--help"
   elif [ $# -eq 1 ]; then
      current_time=$(date "+%Y%m%d%H%M")
      #echo "$current_time"
      fileName=$(echo "$1" | awk -F[/:] '{print $4}'| sed  's/.com/'$current_time'.png/' | sed  's/.co.il/'$current_time'.png/')
      echo "$1 $fileName"
else    
  for i;
  do
    echo "'$i'"
  done
fi
#) | xargs docker run --shm-size=1gb -v `pwd`:/tmp/screenshot docker_capture_web  ## working
#) | xargs docker run -v `pwd`:/tmp/screenshot mokemokechicken/capture_web
#) | xargs docker run -v `pwd`:/tmp/screenshot docker_capture_web_otorio
#) | xargs docker run --shm-size=1gb -v `pwd`:/tmp/screenshot docker_capture_web_otorio
